[VIDEO]
FORCE_RESOLUTION=0
WIDTH=1920
HEIGHT=1080
FULLSCREEN=1

[INPUT_KEYS]
;Set Keycode (decimal value) for each key. See following link for the value list: 
;https://gist.github.com/Extremelyd1/4bcd495e21453ed9e1dffa27f6ba5f69
EXIT=27

[SYSTEM]
;Default data folder is in "%userProfile%/AppData/LocalLow/Sarbakan/09038_Adrenaline_Skyride_Turret/"
;Set this to "1" to save data in "/NVRAM/" folder from game root path.
SAVE_TO_GAME_FOLDER=1