[VIDEO]
FORCE_RESOLUTION=0
WIDTH=1920
HEIGHT=1080
FULLSCREEN=1

[System]
;0 = USA_CARD_SWIPE
;1 = USA_COIN
;2 = CEC_COIN
;3 = CEC_CARD
;4 = DB_CARD
;5 = UK
;6 = EUROPE
;7 = JAPAN
;8 = CHINA,
;9 = AUSTRALIA
CAB_TEMPLATE=6

[INPUT_KEYS]
;Set Keycode (decimal value) for each key. See following link for the value list: 
;https://gist.github.com/Extremelyd1/4bcd495e21453ed9e1dffa27f6ba5f69
P1_START=49
P2_START=50
P1_COIN=53
P2_COIN=54
VOLUME_UP=273
VOLUME_DOWN=274
DBV=55
TEST=48
EXIT=27