[VIDEO]
FORCE_RESOLUTION=0
WIDTH=1920
HEIGHT=1080
FULLSCREEN=1

[INPUT_KEYS]
;Set Keycode (decimal value) for each key. See following link for the value list: 
;https://gist.github.com/Extremelyd1/4bcd495e21453ed9e1dffa27f6ba5f69
P1_START=49
P2_START=50
P1_COIN=53
P2_COIN=54
TEST=48
MENU_SELECT=13
EXIT=27
